---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apple.nishant.ingle
  resources:
  - containerinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apple.nishant.ingle
  resources:
  - containerinjectors/finalizers
  verbs:
  - update
- apiGroups:
  - apple.nishant.ingle
  resources:
  - containerinjectors/status
  verbs:
  - get
  - patch
  - update
